export const PERMISSIONS = {
  VIEW_VIDEO: 1 << 0,
  UPLOAD_VIDEO: 1 << 1,
  EDIT_VIDEO: 1 << 2,
  DELETE_VIDEO: 1 << 3,
  MANAGE_USERS: 1 << 4,
  MANAGE_TENANT: 1 << 5,
  GLOBAL_ADMIN: 1 << 6
} as const;

export const ROLE_CLEARANCE = {
  viewer: PERMISSIONS.VIEW_VIDEO,
  editor:
    PERMISSIONS.VIEW_VIDEO |
    PERMISSIONS.UPLOAD_VIDEO |
    PERMISSIONS.EDIT_VIDEO |
    PERMISSIONS.DELETE_VIDEO,
  admin:
    PERMISSIONS.VIEW_VIDEO |
    PERMISSIONS.UPLOAD_VIDEO |
    PERMISSIONS.EDIT_VIDEO |
    PERMISSIONS.DELETE_VIDEO |
    PERMISSIONS.MANAGE_USERS |
    PERMISSIONS.MANAGE_TENANT,
  super_admin:
    PERMISSIONS.VIEW_VIDEO |
    PERMISSIONS.UPLOAD_VIDEO |
    PERMISSIONS.EDIT_VIDEO |
    PERMISSIONS.DELETE_VIDEO |
    PERMISSIONS.MANAGE_USERS |
    PERMISSIONS.MANAGE_TENANT |
    PERMISSIONS.GLOBAL_ADMIN
} as const;
